/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Initialize the LMDB environment */
export declare function init(dbPath: string): void
/**
 * Set a relationship between two entities
 * rel_type is a string (e.g., "editor", "viewer", "member")
 */
export declare function setRelationship(subject: string, relType: string, object: string): number
/**
 * Get all relationship types between subject and object
 * Returns array of relation type strings (e.g., ["editor", "viewer"])
 */
export declare function getRelationships(subject: string, object: string): Array<string>
/** Delete a relationship */
export declare function deleteRelationship(subject: string, relType: string, object: string): boolean
/**
 * Define what capabilities a relationship type grants on an entity
 * e.g., setCapability("slack", "editor", READ | WRITE | DELETE)
 */
export declare function setCapability(entity: string, relType: string, capMask: number): number
/** Get capability mask for a relationship type on an entity */
export declare function getCapability(entity: string, relType: string): number | null
/** Set inheritance: subject inherits source's relationship to object */
export declare function setInheritance(subject: string, object: string, source: string): number
/** Get inheritance sources for subject's relationship to object */
export declare function getInheritance(subject: string, object: string): Array<string>
/** Delete an inheritance rule */
export declare function deleteInheritance(subject: string, object: string, source: string): boolean
/** Get all subjects that inherit from source for a specific object */
export declare function getInheritorsFromSource(source: string, object: string): Array<string>
/**
 * Get all inheritance rules for an object
 * Returns array of [source, subject] pairs
 */
export declare function getInheritanceForObject(object: string): Array<Array<string>>
/**
 * Set a label for a capability bit on an entity
 * e.g., setCapLabel("myapp", 0x01, "read")
 */
export declare function setCapLabel(entity: string, capBit: number, label: string): void
/** Get label for a capability bit */
export declare function getCapLabel(entity: string, capBit: number): string | null
/**
 * Check what capabilities subject has on object
 * Returns the effective capability mask (0 if no access)
 */
export declare function checkAccess(subject: string, object: string, maxDepth?: number | undefined | null): number
/** Check if subject has specific capability on object */
export declare function hasCapability(subject: string, object: string, requiredCap: number): boolean
/**
 * Batch set relationships
 * Each entry is [subject, rel_type, object]
 */
export declare function batchSetRelationships(entries: Array<Array<string>>): number
/**
 * Batch set capabilities
 * Each entry is [entity, rel_type, cap_mask]
 */
export declare function batchSetCapabilities(entries: Array<Array<string>>): number
/**
 * Batch set inheritance
 * Each entry is [subject, object, source]
 */
export declare function batchSetInheritance(entries: Array<Array<string>>): number
/**
 * List all entities that subject has any relationship with
 * Returns array of [object, rel_type] pairs
 */
export declare function listAccessible(subject: string): Array<Array<string>>
/**
 * List all subjects that have any relationship to object
 * Returns array of [subject, rel_type] pairs
 */
export declare function listSubjects(object: string): Array<Array<string>>
/** Close the database (for cleanup) */
export declare function close(): void
